// <auto-generated />
using System;
using AmazingMicroStore.Infra.DataAccess.Repositories.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AmazingMicroStore.Infra.DataAccess.Migrations
{
    [DbContext(typeof(CatalogProductContext))]
    [Migration("20190828012907_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AmazingMicroStore.ProductCatalogMicroservice.Domain.ProductAggregate.CatalogProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CatalogProductStatus");

                    b.Property<string>("Description");

                    b.Property<decimal>("MinimumPrice");

                    b.Property<string>("Name");

                    b.Property<int>("OffersQuantity");

                    b.Property<Guid>("ProductId");

                    b.HasKey("Id");

                    b.ToTable("CatalogProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
